FROM rabbitmq:4.2.8

ENV VENV_DIR "/python/venv"

RUN apt-get update; \
    apt-get install --yes --no-install-recommends \
        gcc \
        libpq-dev \
        git \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        sqlite3 \
    ;\
    rm -rf /var/lib/apt/lists/*; \

    python3 -m venv $VENV_DIR && . $VENV_DIR/bin/activate && pip install uv

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 4369 5671 5672 15691 15692 25672
CMD ["rabbitmq-server"]
