"""add route community constructs

Revision ID: 18380dc634da
Revises: 032293b44a9c
Create Date: 2026-03-10 15:49:01.918538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18380dc634da"
down_revision: Union[str, Sequence[str], None] = "032293b44a9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

membership_status_enum_name = "membershipstatus"
route_community_fk_constraint_name = "route_community_id_fkey"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "membership_request",
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("community_id", sa.String(length=36), nullable=False),
        sa.Column("route_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UNKNOWN",
                "PENDING",
                "DECLINED",
                "APPROVED",
                name=membership_status_enum_name,
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.PrimaryKeyConstraint("community_id", "route_id"),
    )
    op.add_column(
        "route", sa.Column("community_id", sa.String(length=36), nullable=True)
    )
    op.create_foreign_key(
        route_community_fk_constraint_name,
        "route",
        "community",
        ["community_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(route_community_fk_constraint_name, "route", type_="foreignkey")
    op.drop_column("route", "community_id")
    op.drop_table("membership_request")
    op.drop_table("community")
    op.execute(f"DROP TYPE {membership_status_enum_name}")
    # ### end Alembic commands ###
