"""add duid to user

Revision ID: 3832c52955f5
Revises: d5e523d513bf
Create Date: 2025-12-23 15:42:21.648771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3832c52955f5"
down_revision: Union[str, Sequence[str], None] = "d5e523d513bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

constraint_key = "user_duid_key"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("duid", sa.String(length=128), nullable=True))
    op.create_unique_constraint(constraint_key, "user", ["duid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_key, "user", type_="unique")
    op.drop_column("user", "duid")
    # ### end Alembic commands ###
