"""remove unique constraint on duid

Revision ID: 3acb77dd5d02
Revises: 3832c52955f5
Create Date: 2025-12-29 14:06:25.240094

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3acb77dd5d02"
down_revision: Union[str, Sequence[str], None] = "3832c52955f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("user_duid_key"), "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("user_duid_key"), "user", ["duid"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
