"""add domain table

Revision ID: 3bf5f7623dea
Revises: 3acb77dd5d02
Create Date: 2026-01-13 13:52:10.220770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3bf5f7623dea"
down_revision: Union[str, Sequence[str], None] = "3acb77dd5d02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

fk_constraint_name = "route_domain_id_fkey"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column("restricted", sa.Boolean(), nullable=True),
        sa.Column("default", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("value"),
    )
    op.add_column("route", sa.Column("domain_id", sa.String(length=36), nullable=False))
    op.create_foreign_key(fk_constraint_name, "route", "domain", ["domain_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(fk_constraint_name, "route", type_="foreignkey")
    op.drop_column("route", "domain_id")
    op.drop_table("domain")
    # ### end Alembic commands ###
