"""Add last_contact column to route

Revision ID: 3bfd13c165c0
Revises: b70672394cf4
Create Date: 2025-09-04 12:00:23.578557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from route_registry.store.orm import PendulumDateTime

# revision identifiers, used by Alembic.
revision: str = "3bfd13c165c0"
down_revision: Union[str, Sequence[str], None] = "b70672394cf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("route", sa.Column("last_contact", PendulumDateTime(), nullable=True))
    op.execute("UPDATE route SET last_contact = now() WHERE last_contact is NULL")
    op.alter_column("route", "last_contact", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("route", "last_contact")
    # ### end Alembic commands ###
