"""Drop unique constraint on dst

Revision ID: 671ac85bae45
Revises: 7c9e3af1c8a2
Create Date: 2025-10-07 16:19:30.103176

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "671ac85bae45"
down_revision: Union[str, Sequence[str], None] = "7c9e3af1c8a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("route_dst_key"), "route", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("route_dst_key"), "route", ["dst"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
