"""refactor availability_status to status

Revision ID: 8b2e18c8fb42
Revises: c7f339b17766
Create Date: 2026-01-28 11:03:23.453730

"""

import pendulum
from typing import Sequence, Union

from alembic import op
from contextlib import contextmanager

from sqlalchemy.orm import registry
from sqlalchemy import (
    DateTime,
    Column,
    String,
    ForeignKey,
    Enum,
    Table,
    TypeDecorator,
)


# revision identifiers, used by Alembic.
revision: str = "8b2e18c8fb42"
down_revision: Union[str, Sequence[str], None] = "c7f339b17766"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# enum migration
# NOTE: ordinarily an enum modification wouldn't need to update the type names
# this change just happens to be doing 2 things at once: renaming the type
# and adding new values
old_type_name = "availabilitystatus"
new_type_name = "status"

old_values = ("UP", "DOWN")
new_values_only = ("MISCONFIGURED", "MISSING_ENTITY", "UPGRADE_REQUIRED")
new_values = old_values + new_values_only

old_type = Enum(*old_values, name=old_type_name)
new_type = Enum(*new_values, name=new_type_name)

mapper_registry = registry()


class PendulumDateTime(TypeDecorator):
    impl = DateTime
    cache_ok = True

    def process_bind_param(self, value, dialect):
        """
        Converts a Pendulum datetime to a naive datetime before storing in the DB.
        """
        if isinstance(value, pendulum.DateTime):
            # Convert to UTC and make it naive
            return value.in_tz("UTC").naive()
        return value

    def process_result_value(self, value, dialect):
        """
        Converts a naive datetime from the DB back into a Pendulum datetime.
        """
        if value is not None:
            # Convert naive datetime to a timezone-aware Pendulum datetime in UTC
            return pendulum.instance(value, tz="UTC")
        return value


verification_status_values = ("VERIFIED", "PENDING", "UNVERIFIED")
route_table = Table(
    "route",
    mapper_registry.metadata,
    Column("id", String(36), unique=True, primary_key=True),
    Column("domain_id", String(36), ForeignKey("domain.id"), nullable=False),
    Column("name", String(128), nullable=False),
    Column("src", String(2000), unique=True, nullable=False),
    Column("dst", String(2000), nullable=False),
    Column("token", String(256), unique=True, nullable=False),
    Column("verification_status", Enum(*verification_status_values), nullable=False),
    Column("status", new_type, nullable=False),
    Column("last_contact", PendulumDateTime(), nullable=False),
)


@contextmanager
def type_modifier(type_name: str, tmp_suffix: str = "tmp"):
    "Enable type modification by moving an existing type to a temporary name"

    tmp_type_name = f"{type_name}_{tmp_suffix}"
    op.execute(f"ALTER TYPE {type_name} RENAME TO {tmp_type_name}")

    try:
        yield
    except Exception:
        # restore type on any error
        op.execute(f"ALTER TYPE {tmp_type_name} RENAME TO {type_name}")
        raise
    else:
        op.execute(f"DROP TYPE {tmp_type_name}")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "route", "availability_status", nullable=False, new_column_name="status"
    )
    with type_modifier(old_type_name):
        new_type.create(op.get_bind())
        op.execute(
            f"ALTER TABLE route ALTER COLUMN status TYPE {new_type_name} USING status::text::{new_type_name}"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Modify route table to move all new_type references to DOWN
    (
        op.execute(
            route_table.update()
            .where(route_table.c.status.in_(new_values_only))
            .values(status="DOWN")
        )
    )

    with type_modifier(new_type_name):
        old_type.create(op.get_bind())
        op.execute(
            f"ALTER TABLE route ALTER COLUMN status TYPE {old_type_name} USING status::text::{old_type_name}"
        )

    op.alter_column(
        "route", "status", nullable=False, new_column_name="availability_status"
    )
    # ### end Alembic commands ###
