"""composite community name entity unique constraint

Revision ID: 8ceb564736f7
Revises: 18380dc634da
Create Date: 2026-03-26 09:06:41.475923

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8ceb564736f7'
down_revision: Union[str, Sequence[str], None] = '18380dc634da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

community_name_entity_uq_constraint = "community_entity_id_name_key"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(community_name_entity_uq_constraint, 'community', ['entity_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(community_name_entity_uq_constraint, 'community', type_='unique')
    # ### end Alembic commands ###
