"""add admin token table and is_admin to user

Revision ID: 982b0a2b0550
Revises: 8ceb564736f7
Create Date: 2026-06-01 16:07:50.640308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982b0a2b0550'
down_revision: Union[str, Sequence[str], None] = '8ceb564736f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    adminrole_enum = sa.Enum('ANY', 'OBSERVER', 'DOMAIN', 'IDENTITY', 'NONE', name='adminrole')
    op.create_table('admin_token',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('value', sa.String(length=128), nullable=False),
        sa.Column('role', adminrole_enum, nullable=False, server_default=sa.text("'NONE'")),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('value')
    )
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_table('admin_token')
    adminrole_enum = sa.Enum('ANY', 'OBSERVER', 'DOMAIN', 'IDENTITY', 'NONE', name='adminrole')
    adminrole_enum.drop(op.get_bind(), checkfirst=True)
# ### end Alembic commands ###
