"""Initial commit

Revision ID: b70672394cf4
Revises:
Create Date: 2025-08-26 10:57:25.886233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b70672394cf4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "route",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("src", sa.String(length=2000), nullable=False),
        sa.Column("dst", sa.String(length=2000), nullable=False),
        sa.Column("token", sa.String(length=256), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum("VERIFIED", "PENDING", "UNVERIFIED", name="verificationstatus"),
            nullable=False,
        ),
        sa.Column(
            "availability_status",
            sa.Enum("UP", "DOWN", name="availabilitystatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dst"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("src"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "group",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "rule",
        sa.Column("route_id", sa.String(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("policy", sa.Enum("ALLOW", "DENY", name="policy"), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.PrimaryKeyConstraint("route_id", "entity_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("uid", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("rule")
    op.drop_table("group")
    op.drop_table("route")
    op.drop_table("entity")
    # ### end Alembic commands ###
