"""add domain type to domain table

Revision ID: c7f339b17766
Revises: 3bf5f7623dea
Create Date: 2026-01-14 10:48:21.679815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7f339b17766"
down_revision: Union[str, Sequence[str], None] = "3bf5f7623dea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


domain_unique_id = "domain_id_key"
domain_type_enum = sa.Enum("STANDARD", "EPHEMERAL", "USER", name="domaintype")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    domain_type_enum.create(op.get_bind())
    op.add_column(
        "domain",
        sa.Column(
            "domain_type", domain_type_enum, server_default="STANDARD", nullable=False
        ),
    )
    op.create_unique_constraint(domain_unique_id, "domain", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(domain_unique_id, "domain", type_="unique")
    op.drop_column("domain", "domain_type")
    domain_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
