"""Link entity and route via many to many

Revision ID: d5e523d513bf
Revises: 671ac85bae45
Create Date: 2025-10-15 10:46:35.095784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5e523d513bf"
down_revision: Union[str, Sequence[str], None] = "671ac85bae45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_route_association",
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("route_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.PrimaryKeyConstraint("entity_id", "route_id"),
    )
    op.create_unique_constraint(None, "entity", ["id"])
    op.create_unique_constraint(None, "route", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "route", type_="unique")
    op.drop_constraint(None, "entity", type_="unique")
    op.drop_table("entity_route_association")
    # ### end Alembic commands ###
