apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "route-registry.fullname" . }}
  labels:
    {{- include "route-registry.labels" . | nindent 4 }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ .Values.global.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "route-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "route-registry.labels" . | nindent 8 }}
        {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "route-registry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Values.volumes.name }}
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
            - name: DYNACONF_DB__username
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: {{ .Values.postgres.userKey }}
            - name: DYNACONF_DB__password
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: {{ .Values.postgres.passwordKey }}
            - name: DYNACONF_RABBITMQ__password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
            - name: DYNACONF_RABBITMQ__username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username
          envFrom:
            - configMapRef:
                name: route-registry
            - secretRef:
                name: route-registry
          volumeMounts:
            - name: {{ .Values.volumes.name }}
              mountPath: {{ .Values.volumes.mountPath }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: route-registry
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.global.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.global.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.global.resources | nindent 12 }}
          {{- with .Values.global.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["bash", "/app/scripts/migrate-db"]
          env:
            - name: DYNACONF_DB__username
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: {{ .Values.postgres.userKey }}
            - name: DYNACONF_DB__password
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: {{ .Values.postgres.passwordKey }}
          envFrom:
            - configMapRef:
                name: route-registry
            - secretRef:
                name: route-registry
      {{- with .Values.global.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
